### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by GFdevelop** [virtualsquare/purelibc#1]
OS: Arch Linux

```
[ 16%] Building C object CMakeFiles/purelibc.dir/syscalls.c.o
........../syscalls.c:56:10: fatal error: ustat.h: File o directory non esistente
 #include <ustat.h>
          ^~~~~~~~~
compilation terminated.
```

Man ustat (2) notes declare:

> ustat() is deprecated and has been provided only for compatibility.
>        All new programs should use statfs(2) instead.

My OS don't provide ustat.h?

**Comment by rd235** [comment]
fisex in d455939
